// ng/src/app/components/ui/builder/builder.component.ts
import { Component, Input, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ButtonComponent } from '../button/button.component';
import { ContentComponent } from '../content/content.component';

@Component({
  selector: 'app-builder',
  standalone: true,
  imports: [CommonModule, RouterLink, ButtonComponent, ContentComponent],
  template: `
    @if (hasValidData()) {
      @for (component of data().zone; track component.id || $index) {
        <section>
          @switch (component.__component) {
            @case ('cms.content') {
              <app-content [data]="component"></app-content>
            }
            @case ('cms.button') {
              <a
                [routerLink]="component.to"
                [target]="component.blank ? '_blank' : undefined">
                <app-button>{{ component.value }}</app-button>
              </a>
            }
            @default {
              <!-- Weitere Komponenten werden später hinzugefügt -->
            }
          }
        </section>
      }
    } @else {
      <div class="error-message">404 – Seite nicht gefunden</div>
    }
  `,
  styleUrls: ['./builder.component.scss']
})
export class BuilderComponent {
  @Input() set inputData(value: any) {
    this.data.set(value);
  }

  data = signal<any>(null);

  hasValidData = computed(() => {
    const currentData = this.data();
    return currentData && Array.isArray(currentData.zone);
  });
}

// react/app/components/ui/builder.tsx
import React from "react";
import {Image} from "~/components/ui/image";
import {Content} from "~/components/ui/content";
import {Button} from "~/components/ui/button";
import {Link} from "react-router";
import {Space} from "~/components/ui/space";
import {PostList} from "~/components/ui/post-list";
import {ContentImage} from "~/components/ui/content-image";
import {Table} from "~/components/ui/table";

export const Builder = ({data}: any) => {
    if (!data || !Array.isArray(data.zone)) {
        return <div>404 – Seite nicht gefunden</div>;
    }

    const renderComponent = (component: any) => {
        switch (component.__component) {
            case "cms.image":
                return (
                    <section className="">
                        <Image data={component}/>
                    </section>
                );
            case "cms.content":
                return (
                    <section className="">
                        <Content data={component}/>
                    </section>
                );
            case "cms.button":
                return (
                    <section className="">
                        <Link target={component.blank ? "_blank" : undefined} to={component.to}>
                            <Button>{component.value}</Button>
                        </Link>
                    </section>
                );
            case "cms.space":
                return (
                    <section className="">
                        <Space data={component}/>
                    </section>
                );
            case "cms.post-list":
                return (
                    <section className="">
                        <PostList data={component}/>
                    </section>
                );
            case "cms.content-image":
                return (
                    <section className="">
                        <ContentImage data={component}/>
                    </section>
                );
            case "cms.table":
                return (
                    <section className="">
                        <Table data={component}/>
                    </section>
                );
            default:
                return null;
        }
    };

    return (
        <>
            {data.zone.map((component: any, index: any) => (
                <React.Fragment key={index}>
                    {renderComponent(component)}
                </React.Fragment>
            ))}
        </>
    );
};
